<h2>New Post</h2>

<?= '<pre>'.var_export($p,1).'</pre>' ?>

<?= $this->tag->form('posts/create') ?>
    <div class="form-group">
        <label for="title">Título</label>
        <?= $form->render('title') ?>
        <span class="text text-danger"><?= $errors['title'] ?? '' ?></span>
    </div>

    <div class="categories form-group">
        <label for="categories">Categories</label>

        <div class="category">
            <?= Phalcon\Tag::select(['category[]', Categories::find(), 'using' =>['id', 'name']]) ?>
            <a href="#" class="new-category btn btn-light" onclick="addCategory()">+</a>
        </div>
    </div>

    <div class="form-group">
        <label for="body">Corpo</label>
        <?= $form->render('body') ?>
    </div>

    <div>
        <label for="published"><?= $form->render('published') ?> Published</label>
    </div>

    <div class="pubdate d-none">
        <?= $form->render('publishing_date') ?>
    </div>

    <br>
    <?= $this->tag->submitButton('Register'); ?>
</form>

<script>
    var published = document.querySelector('#published')
    var pubdate = document.querySelector('.pubdate')
    published.onchange = () => {
        pubdate.className = 'pubdate d-' + (published.checked ? 'block' : 'none')
    };
</script>

<script>
    var catDiv = document.querySelector('.categories');
    var catIds = JSON.parse('<?= json_encode($categories) ?>');

    function addCategory() {
        let size = catDiv.querySelectorAll('.category').length;

        if (size >= catIds.length) {
            return;
        }

        catDiv.innerHTML += `
            <div class="category">
                <?= Phalcon\Tag::select(['category[]', Categories::find(), 'using' =>['id', 'name']]) ?>
                <a href="#" class="btn btn-light" onclick="addCategory(); return false">+</a>
            </div>
        `;
    }
</script>