<h2>Edit Post</h2>

<?= $this->tag->form('posts/edit/' .$post->id) ?>
    <div class="form-group">
        <label for="title">Título</label>
        <?= $form->render('title', ['value' => $post->title]) ?>
        <span class="text text-danger"><?= $errors['title'] ?? '' ?></span>
    </div>

    <div class="form-group">
        <label for="body">Corpo</label>
        <?= $form->render('body', ['value' => $post->body]) ?>
    </div>

    <?= $this->tag->submitButton('Save'); ?>
</form>