<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
    <header class="d-flex flex-columns flex-md-row align-items-center py-4 bg-white border-bottom shadow-sm">
        <div class="container">
            <a href="<?= $this->url->getBaseUri() ?>" class="logo my-0 mr-md-auto h4 text-dark">Phalcon Tutorial</a>
        </div>
    </header>

    <div class="container my-3"><?= $this->getContent() ?></div>
</body>
</html>