<h3>Entities</h3>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Entity</th>
            <th>Records</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><a href="users">Users</a></td>
            <td><?= $users ?></td>
        </tr>
        <tr>
            <td><a href="posts">Posts</a></td>
            <td><?= $posts ?></td>
        </tr>
        <tr>
            <td><a href="categories">Categories</a></td>
            <td><?= $categories ?></td>
        </tr>
    </tbody>
</table>