<?php use Phalcon\Tag ?>
<?php $this->tag->setDoctype(Tag::HTML5) ?>
<?= $this->tag->getDoctype() ?>
<html lang="pt-br">
<head>
</head>
<body>
    <h1>Home</h1>
    <?= $this->tag->linkTo(['signup', 'Sign Up!', 'class' => 'btn btn-primary']) ?>

    <br>
    <br>
    <h2>List of Users</h2>
    <br>

    <table class="table table-bordered table-hover">
        <thead class="hthead-light">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>E-mail</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $u): ?>
            <tr>
                <td><?= $u->id ?></td>
                <td><?= $u->name ?></td>
                <td><?= $u->email ?></td>
                <td>
                    <?= $this->tag->linkTo(['signup/edit/' .$u->id, 'Edit', 'class' => 'btn btn-primary']) ?>
                    <?= $this->tag->linkTo(['signup/delete/' .$u->id, 'Delete', 'class' => 'btn btn-danger', 'onclick' => 'return confirm(\'Are you sure you want to delete this user?\')']) ?>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Users quantity: <?= $users->count() ?></td>
            </tr>
        </tfoot>
    </table>
</body>
</html>