<h2>Edit</h2>

<?php echo $this->tag->form('signup/edit/' .$user->id); ?>
    <div class="form-group">
        <label for="name">Name</label>
        <?php echo $this->tag->textField(['name', 'class' => 'form-control', 'value' => $user->name ?? '']); ?>
        <span class="text-danger"><?= $errors['name'] ?? '' ?></span>
    </div>

    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField(['email', 'class' => 'form-control', 'value' => $user->email ?? '']); ?>
        <span class="text-danger"><?= $errors['email'] ?? '' ?></span>
    </div>

    <p>
        <?php echo $this->tag->submitButton('Save'); ?>
    </p>

</form>