<?php use Phalcon\Tag ?>
<?php $this->tag->setDoctype(Tag::HTML5) ?>
<?= $this->tag->getDoctype() ?>
<html lang="pt-br">
<head>
</head>
<body>
    <h1>Categories</h1>
    <?= $this->tag->linkTo(['categories/create', 'New Category', 'class' => 'btn btn-primary']) ?>
    
    <?= $this->flash->output() ?>

    <?php if ($categories->count() == 0): ?>
    <?php else: ?>
    <br>
    <br>

    <?php if (isset($msg)): ?>
    <div class="alert alert-success" role="alert">
        <?= $msg ?>
    </div>
    <?php endif ?>

    <h2>List of Categories</h2>
    <br>

    <table class="table table-bordered table-hover">
        <thead class="hthead-light">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categories as $c): ?>
            <tr>
                <td><?= $c->id ?></td>
                <td><?= $c->name ?></td>
                <td>
                    <?= $this->tag->linkTo(['categories/edit/' .$c->id, 'Edit', 'class' => 'btn btn-primary']) ?>
                    <?= $this->tag->linkTo(['categories/delete/' .$c->id, 'Delete', 'class' => 'btn btn-danger', 'onclick' => 'return confirm(\'Are you sure you want to delete this category?\')']) ?>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Categories quantity: <?= $categories->count() ?></td>
            </tr>
        </tfoot>
    </table>
    <?php endif ?>
</body>
</html>